# Generated by Django 6.0.2 on 2026-02-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employeeId',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
