# Generated by Django 6.0.2 on 2026-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employeeId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
